/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package trans


import org.gradle.api.Plugin
import org.gradle.api.Project

/**
 * A simple 'hello world' plugin.
 */
public class TransPlugin implements Plugin<Project> {
    public void apply(Project project) {
        // Register a task
        project.tasks.create("trans", Trans.class, "")



        def android = project.extensions.getByType(AppExtension)
        android.registerTransform(new TransTRRRR(project))

        project.task('transformPath') {
            doLast {
                System.out.println('+++++++++++++++++++++transformPath task')
            }
        }
    }
}
